/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/admin/AdminLayout.vue')['default']
    AdminSection: typeof import('./components/admin/AdminSection.vue')['default']
    AlbumEditorWorkspace: typeof import('./components/admin/AlbumEditorWorkspace.vue')['default']
    ArticleEditorWorkspace: typeof import('./components/admin/ArticleEditorWorkspace.vue')['default']
    DailyEditorWorkspace: typeof import('./components/admin/DailyEditorWorkspace.vue')['default']
    ImageUploadHintCard: typeof import('./components/admin/ImageUploadHintCard.vue')['default']
    PageEditorWorkspace: typeof import('./components/admin/PageEditorWorkspace.vue')['default']
    ProjectEditorWorkspace: typeof import('./components/admin/ProjectEditorWorkspace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
