/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/albums': RouteRecordInfo<'/albums', '/albums', Record<never, never>, Record<never, never>, '/albums/edit/[id]' | '/albums/new'>,
    '/albums/edit/[id]': RouteRecordInfo<'/albums/edit/[id]', '/albums/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/albums/new': RouteRecordInfo<'/albums/new', '/albums/new', Record<never, never>, Record<never, never>>,
    '/articles': RouteRecordInfo<'/articles', '/articles', Record<never, never>, Record<never, never>, '/articles/edit/[id]' | '/articles/new'>,
    '/articles/edit/[id]': RouteRecordInfo<'/articles/edit/[id]', '/articles/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/articles/new': RouteRecordInfo<'/articles/new', '/articles/new', Record<never, never>, Record<never, never>>,
    '/comments': RouteRecordInfo<'/comments', '/comments', Record<never, never>, Record<never, never>>,
    '/dailies': RouteRecordInfo<'/dailies', '/dailies', Record<never, never>, Record<never, never>, '/dailies/edit/[id]' | '/dailies/new'>,
    '/dailies/edit/[id]': RouteRecordInfo<'/dailies/edit/[id]', '/dailies/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dailies/new': RouteRecordInfo<'/dailies/new', '/dailies/new', Record<never, never>, Record<never, never>>,
    '/friends': RouteRecordInfo<'/friends', '/friends', Record<never, never>, Record<never, never>>,
    '/install': RouteRecordInfo<'/install', '/install', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/pages': RouteRecordInfo<'/pages', '/pages', Record<never, never>, Record<never, never>, '/pages/edit/[id]' | '/pages/new'>,
    '/pages/edit/[id]': RouteRecordInfo<'/pages/edit/[id]', '/pages/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pages/new': RouteRecordInfo<'/pages/new', '/pages/new', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>, '/projects/edit/[id]' | '/projects/new'>,
    '/projects/edit/[id]': RouteRecordInfo<'/projects/edit/[id]', '/projects/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/projects/new': RouteRecordInfo<'/projects/new', '/projects/new', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>, '/settings/backup-restore' | '/settings/mail-management' | '/settings/mail-notify'>,
    '/settings/backup-restore': RouteRecordInfo<'/settings/backup-restore', '/settings/backup-restore', Record<never, never>, Record<never, never>>,
    '/settings/mail-management': RouteRecordInfo<'/settings/mail-management', '/settings/mail-management', Record<never, never>, Record<never, never>>,
    '/settings/mail-notify': RouteRecordInfo<'/settings/mail-notify', '/settings/mail-notify', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/albums.vue': {
      routes: '/albums' | '/albums/edit/[id]' | '/albums/edit' | '/albums/new'
      views: 'default'
    }
    'src/pages/albums/edit/[id].vue': {
      routes: '/albums/edit/[id]'
      views: never
    }
    'src/pages/albums/new.vue': {
      routes: '/albums/new'
      views: never
    }
    'src/pages/articles.vue': {
      routes: '/articles' | '/articles/edit/[id]' | '/articles/edit' | '/articles/new'
      views: 'default'
    }
    'src/pages/articles/edit/[id].vue': {
      routes: '/articles/edit/[id]'
      views: never
    }
    'src/pages/articles/new.vue': {
      routes: '/articles/new'
      views: never
    }
    'src/pages/comments.vue': {
      routes: '/comments'
      views: never
    }
    'src/pages/dailies.vue': {
      routes: '/dailies' | '/dailies/edit/[id]' | '/dailies/edit' | '/dailies/new'
      views: 'default'
    }
    'src/pages/dailies/edit/[id].vue': {
      routes: '/dailies/edit/[id]'
      views: never
    }
    'src/pages/dailies/new.vue': {
      routes: '/dailies/new'
      views: never
    }
    'src/pages/friends.vue': {
      routes: '/friends'
      views: never
    }
    'src/pages/install.vue': {
      routes: '/install'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/media.vue': {
      routes: '/media'
      views: never
    }
    'src/pages/pages.vue': {
      routes: '/pages' | '/pages/edit/[id]' | '/pages/edit' | '/pages/new'
      views: 'default'
    }
    'src/pages/pages/edit/[id].vue': {
      routes: '/pages/edit/[id]'
      views: never
    }
    'src/pages/pages/new.vue': {
      routes: '/pages/new'
      views: never
    }
    'src/pages/projects.vue': {
      routes: '/projects' | '/projects/edit/[id]' | '/projects/edit' | '/projects/new'
      views: 'default'
    }
    'src/pages/projects/edit/[id].vue': {
      routes: '/projects/edit/[id]'
      views: never
    }
    'src/pages/projects/new.vue': {
      routes: '/projects/new'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings' | '/settings/backup-restore' | '/settings/mail-management' | '/settings/mail-notify'
      views: 'default'
    }
    'src/pages/settings/backup-restore.vue': {
      routes: '/settings/backup-restore'
      views: never
    }
    'src/pages/settings/mail-management.vue': {
      routes: '/settings/mail-management'
      views: never
    }
    'src/pages/settings/mail-notify.vue': {
      routes: '/settings/mail-notify'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
