[source.crates-io]
replace-with = "aliyun-sparse"

[source.aliyun-sparse]
registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"

[net]
retry = 10
git-fetch-with-cli = true

[http]
timeout = 120
multiplexing = false
